// IPC 通道名常量（主/预加载/渲染共享，避免拼写漂移）

export const IPC = {
  // invoke (renderer -> main, 有返回值)
  configGet: 'config:get',
  configSet: 'config:set',
  configTest: 'config:test',
  configBalance: 'config:balance',
  projectOpen: 'project:open',
  sessionsLoad: 'sessions:load',
  sessionsSave: 'sessions:save',
  agentSend: 'agent:send',
  agentAbort: 'agent:abort',
  agentReset: 'agent:reset',
  toolApprove: 'tool:approve',
  dataInfo: 'data:info',
  dataClear: 'data:clear',
  // 文件列表与预览
  projectTree: 'project:tree',
  fileRead: 'file:read',
  pickPath: 'pick:path',
  mentionResolve: 'mention:resolve',
  fileReadBinary: 'file:read-binary',
  shellOpen: 'shell:open',
  memoryGet: 'memory:get',
  memoryAdd: 'memory:add',
  fileWrite: 'file:write',
  fileSearch: 'file:search',
  modelFim: 'model:fim',
  skillsList: 'skills:list',
  skillRead: 'skills:read',
  skillSave: 'skills:save',
  skillInstall: 'skills:install',
  skillDiscover: 'skills:discover',
  skillDelete: 'skills:delete',
  mcpStatus: 'mcp:status',
  mcpAdd: 'mcp:add',
  mcpRemove: 'mcp:remove',
  mcpReload: 'mcp:reload',
  marketList: 'market:list',
  marketSearch: 'market:search',
  marketInstall: 'market:install',
  shellOpenUrl: 'shell:open-url',
  skillUpdate: 'skills:update',
  dataOpen: 'data:open',
  taskStart: 'task:start',
  taskList: 'task:list',
  taskCancel: 'task:cancel',
  // 终端
  termExec: 'term:exec',
  termInput: 'term:input',
  termKill: 'term:kill',
  termCd: 'term:cd',
  // event (main -> renderer, 单向推送)
  agentEvent: 'agent:event',
  termEvent: 'term:event',
  taskEvent: 'task:event'
} as const
